apiVersion: v1
kind: ConfigMap
metadata:
  name: whatnot-else-config
  namespace: whatnot-else
data:
  FRAPPE_SITE: "whatnotelse.com"
  REDIS_CACHE: "redis://whatnot-redis-cache.whatnot-else.svc.cluster.local:6379"
  REDIS_QUEUE: "redis://whatnot-redis-queue.whatnot-else.svc.cluster.local:6379"
  REDIS_SOCKETIO: "redis://whatnot-redis-socketio.whatnot-else.svc.cluster.local:6379"
  DB_HOST: "whatnot-mariadb.whatnot-else.svc.cluster.local"
  DB_PORT: "3306"
  OLLAMA_ENDPOINT: "http://ollama.ollama.svc.cluster.local:11434"
