apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatnot-sites-pvc
  namespace: whatnot-else
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatnot-mariadb-pvc
  namespace: whatnot-else
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
